### ISSUE TITLE
[Arduino] Lua server and custom build

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#169]
This build is a custom backend written in Lua designed to run on Arduino devices (like the Yun). The goal of this build is to mirror the Node version, but optimize for space-usage without sacrificing [too many] features.

It only depends on a few libraries and is written very close to "the metal". It is designed to run on uHTTPd.

**NEEDS TESTING**

## Links

- https://github.com/andersevenrud/OS.js-v2/tree/arduino
- https://github.com/andersevenrud/OS.js-v2/wiki/Device:-Arduino-Yun

## TODOs

- [x] Figure out dependencies
- [x] Custom device config file
- [x] Custom build batch
- [x] Build image minification (removal of unused files)
- [x] CGI Server
- [x] FS: Read
- [x] FS: Write
- [x] FS: Scandir
- [x] FS: Move, Copy, Rename, Delete
- [x] FS: MIME **needs to be a bit loser with patterns, but later**
- [x] FS: Upload
- [x] Core API
- [x] Application API
- [x] Curl API
- [x] System Login
- [ ] HTTP GET/POST UTF-8 Guarantee
- [ ] HTTP Buffered GET/POST requests (planned, [howto](http://lists.luaforge.net/pipermail/kepler-project/2010-September/004307.html))
- [ ] HTTP Streaming (extra feautre, not prioritized)
- [ ] HTTP Sessions **in progress. Cookies work for now**
- [ ] Development Environment Documentation **in progress on wiki**
- [x] System: Get system info
- [x] System: Get network device info
- [x] System: Set password **in progress**
- [x] System: Configure WIFI **in progress*
- [ ] System: Configure Firewall
- [x] System: Watch system logs
- [ ] System: View processes **in progress**
- [x] System: View advanced network info
- [ ] System: GPIO
- [x] System: Generic system calls

**Comment by andersevenrud** [comment]
![Screenshot](http://i.imgur.com/skAbiis.png)

**Comment by andersevenrud** [comment]
![Screenshot](http://i.imgur.com/oU8BxAM.png)

**Comment by andersevenrud** [comment]
I am closing this issue, because it belongs to a forker repository. Any updates will be handled internally by the designated team.
