### ISSUE TITLE
[Core] General API/VFS and base Applications

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#304]
Before hitting an eventual *beta*, OS.js needs to nail down API and VFS "backend" methods and client integration.

Recently I've gotten some really good feeback that has *finally* initiated this process.

## Core

- [ ] **Add composition to handler to avoid duplicate code**
- [x] User Management for Handlers (#383)
- [ ] Look into making an Express supported middleware layer (#470)

## Packages

- [x] Add support for less compile via metadata
- [x] Add support for before/after hooks via metadata

## Applications

- [ ] Implement search in FileManager (#385)

## API

- [x] New descriptive URIs #302
- [x] Refactor node server HTTP handling for "descriptive URIs"
- [x] Refactor php server HTTP handling for "descriptive URIs"
- [x] Group permission for apps (#105)
- [x] Blacklisting of apps per-user
- [ ] "Countable" locales (#291)
- [x] Add `checkVFSPrivilege()` (VFS per-user permissions hook)
- [x] Add `checkPackagePrivilege()` (Package per-user permissions hook)
- [ ] server-php does not support package permissions right now
- [x] Copy/Paste files via keyboard
- [x] Add `Application::_api()` with the default pattern and deprecate `Application::_call()` (over the next releases)
- [ ] Improve Search APIs (#385)

## VFS

- [ ] Check if mount is readonly before trying something (Should be implemented. No error in filemanger) ?
- [x] New namespace for "transports"
- [x] Better Handler integration #302 
- [x] Better dataSource handling on server
- [x] Add support for mounting/unmounting client supported modules
- [x] Add support for HTTP proxy file getting (including config/setting)
- [x] Abstraction for VFS Modules in client
- [x] Improve application error handling (in some cases like FileManager it will "hang")
- [x] "Spring cleanup"
- [ ] Progress dialogs (realtime) on all VFS modules
- [ ] Read last modified timestamp on save functions
- [x] WebDAV support (#297)
- [x] OwnCloud support (#297)
- [ ] Extended DAV support (#297)
- [ ] DAV Auth Header  [doc ](https://github.com/owncloud/smashbox/blob/master/protocol/protocol.md#authorization)
- [ ] Send multiple operations over VFS methods
- [ ] Indexed file trees for quicker searches
- [x] Disabling of default mounts (like osjs/apps) via `src/conf`

# Misc

- [x] Update homepage docs
- [x] Ensure NW still works fine in nightly
- [x] Ensure this transitions into Arduino branch/codebase
- [x] Add docs/examples on how to do permissions

**Comment by andersevenrud** [comment]
@RickGlimmer This issue now superseeds #302 and #303.

**Comment by andersevenrud** [comment]
FYI: I am merging this into `master` as we speak :)

**Comment by andersevenrud** [comment]
@RickGlimmer Thoughts on the changes ? :)

**Comment by RickGlimmer** [comment]
I am testing them right now. :) It is a lot easier to work with that is for sure! :+1:

**Comment by RickGlimmer** [comment]
The write could be a bit easier. :)
It is now:
{ data: "data:image/png;base64,iVBOR...."
path: "home:////New file.png" }

If you can split the data it would be great. Maybe like this:
{ path: "home:///New files.png", mime: "image/png", encoding: "base64", data: "iVBOR....."

**Comment by andersevenrud** [comment]
The "problem" is that the `data` is made with the browser APIs and comes with full data uri. Relevant: https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs

I don't want to perform any string-type operations on this in the client (effectively doubles the needed ram usage).

The server assumes that `write` comes with base64 unless the `raw` options flag is set (binary).

**Comment by andersevenrud** [comment]
@RickGlimmer This problem can somewhat be "solved" another way. Instead of relying on `write` function on the server, it is possible to simply use the browser upload functinality. That way the transport is always arraybuffer.

It's something I'm considering.

But as you said, this made it a bit easier to work with, and avoid confusions with nested JSON to the APIs. Also debugging is a bit better in the browser now since it makes a distinct entry in the network monitor (no more "API" only. It actually shows the method used)

**Comment by junland** [comment]
+1 for group permissions :)

**Comment by RickGlimmer** [comment]
I am not a fan of datauris because once they start to get bigger they slow down things considerably and they can be easily abused. I am not sure if getting a bytearray from a canvas (draw app) is possible so it might be the only way to do it. Converting base64 to bytearray is costly and any conversion should be avoided when possible.

My requirements are a bit out of the ordinary and i am very happy that you allowed a custom driver to be made that allows me to adapt for those requirements. One of the requirements is that no GET's are allowed, only POST. Each request has to have a authorization token that is refreshed every 5 minutes. It helps avoiding people sharing those URL's directly in messenger type of applications and emails.

In my handler i will just use your datauri and post it so that it can be processed on the server. Splitting and manipulating it client side is then prevented. So no problem if it stays like it is. :)

**Comment by RickGlimmer** [comment]
Found a small discrepancy in naming
```javascript
    if ( method === 'FS:xhr' ) {
      return this.__callGET(args, options, cbSuccess, cbError);
    } else if ( method === 'FS:upload' ) {
      return this.__callPOST(args, options, cbSuccess, cbError);
    }
```
Wondering if it would be better if xhr is changed into get.

I also found that when i load a user application (menu->System->Test), like on the demo, the request for the .js and .css files do not go through the handler. In my case that results in not being able to load that file. It is a request with this url: http://mydomain.com/FS/get/home:///.packages/Test/main.js . I expected it to be a FS:xhr.

The loading of home:///.packages/packages.json right after the login does go through the custom handler.

**Comment by andersevenrud** [comment]
> I am not a fan of datauris because once they start to get bigger they slow down things considerably and they can be easily abused. 

Not a fan either, but

> One of the requirements is that no GET's are allowed, only POST.
> , the request for the .js and .css files do not go through the handler.

GET is used for resource loading, how are you supposed to get around this ?  Oo

> Wondering if it would be better if xhr is changed into get.

Yeah, I realised this a bit to late. It should be changed, for sure.

**Comment by RickGlimmer** [comment]
If there is a get in the osjs that is not in home/shared/os.js folders then it just passes the handler. I don't need to stop gets that just load a css file or a script only when they are in those directories as i need to keep user data absolutely separated. Also shared folder is only between users of the same organisation. The handler stuffs a authorizationtoken in the request and the backend makes sure that it only honors that request when the token is valid.

**Comment by andersevenrud** [comment]
> as i need to keep user data absolutely separated

So you're doing permission based VFS ?

**Comment by andersevenrud** [comment]
> The current frontend is a older style website in need of modernization. :)

Not sure what you mean by this

**Comment by RickGlimmer** [comment]
I already have a working backend with users. Each user has its own private folder and a shared folder that is shared between users from the same company/organization. Those folders are protected against access with a token. To prevent users copy/pasting URLs all requests for data in those folders is through a POST which contains a token in the body or header. Once a users logs in he gets a token that is valid for 5 minutes. The backend checks this against its database and when correct it honors the request and returns the data. The token is now in the body but is being migrated to a request header to accommodate uploading which is not a functionality right now.
If you want i can give you a login to see how the requests are done, easy to see with chrome network tab.,
I realize this is not common at all, but if i can get this working by just adding the right code in the customs handler it is a good test to see how modular the VFS is.

**Comment by andersevenrud** [comment]
It sounds like you're doing permission based VFS, yes. I started working on group-based permissions yesterday, and plan to finish it today. Tokens is probably something I'll look into later (for *all* requests. This can be done for GET requests by hooking into the transport path() function and append the token to the URL).

**Comment by RickGlimmer** [comment]
Just as some info, this is how the request looks like for a scandir:
Request URL:http://mydomain.com/FS/scandir
Request Method:POST
Status Code:200 OK
Remote Address:10.10.10.10:80
Response Headers
Cache-Control:no-cache
Content-Length:345
Content-Type:application/json; charset=utf-8
Date:Fri, 29 Jan 2016 15:20:36 GMT
Expires:-1
Pragma:no-cache
Server:Microsoft-IIS/8.5
X-AspNet-Version:4.0.30319
X-Powered-By:ASP.NET
Request Headers
Provisional headers are shown
Content-Type:application/json
Origin:http://history.cloud.tilaa.com
Referer:http://history.cloud.tilaa.com/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:CEC005AD-A20A-491B-BA56-E20FC73D6BCD
Request Payload
view source
{token: "F13693A3-6165-485D-9DF1-DFD21E01D281", path: "home:///.packages"}
path: "home:///.packages"
token: "F13693A3-6165-485D-9DF1-DFD21E01D281"

**Comment by andersevenrud** [comment]
Yeah. That's how I imagined it :)

**Comment by RickGlimmer** [comment]
When i click on a menu item of a application (test1) that is installed in the home directory of the user i do not get that request in the custom handler. Sofar that is the only exception i have found. There might be some others but i did not encounter them.

**Comment by andersevenrud** [comment]
User Installed applications is something that is not finished yet, so I'll add that as a task above :)

**Comment by RickGlimmer** [comment]
A gotcha on a windows server running IIS is that some characters are not allowed in a URL. It can be modified but it is there for a reason.
The characters are <,>,*,%,:,&
As you are using a ":" as part of the url the request is being killed on a very early moment in the pipeline, even before it reaches asp.net code. It is not catchable.
a url like this:
http://mydomain.com/FS/get/home:///.packages/Test/main.js 
causes that problem as a ":" is in it.
For people who want to run this on a windows server this is pretty important. It can be solved but it is not something most people know. And if it can be avoided, the better.

The error that is shown is:
A potentially dangerous Request.Path value was detected from the client (:).

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

**Comment by andersevenrud** [comment]
Remember, OS.js is designed to run on the Node server. I already maintain a working PHP server, which is a pain. If someone wants to run it on anything else (like you did) it is pretty much outside the "official support zone" or whatever you'd call it.

> For people who want to run this on a windows server this is pretty important. It can be solved but it is not something most people know. And if it can be avoided, the better.

The best way to solve it is to simply change the path to a escaped query parameter instead of a path.

> For people who want to run this on a windows server this is pretty important. It can be solved but it is not something most people know. And if it can be avoided, the better.

Another thing... if someone is already customizing it to run on ISS, I'd imagine they have enough knowledge to figure out how to make it work ... right !?

---

Hope I'm not coming through as negative. It's just that I'm basically completelty alone when it comes to development of this project, and I have to put a line somewhere as what I can do about all this at the moment (but of course you can modify whatever you want to make it work in your usecase) :P

**Comment by RickGlimmer** [comment]
I understand. It is not that big of a deal as it is solvable.
However this is probably something like 99% of people working on IIS do not know and it is a pain to get it allowed. Even if they find the solution it is often forbidden by IT or even hosts.

My request is if the ":" can be dropped or maybe changed into a character that is allowed. You would then have no future questions why it is not running on IIS. :)

**Comment by andersevenrud** [comment]
I just did a google search on the error and the first link had the solution. Hehe.

> My request is if the ":" can be dropped or maybe changed into a character that is allowed. You would then have no future questions why it is not running on IIS. :)

Would it work if I used:

```
/FS/get/?path={urlencodedpath}
```

?

That is the simplest solution

**Comment by RickGlimmer** [comment]
It is more these kind of requests:
http://osjsv2.0o.no/FS/get/home:///.packages/Test/main.js

They are not going through the custom handler ( i expected that first).
I saw that this particular case is a bit more difficult as it is used for the src attribute of a script tag that is added to the page.

If your intention is to let that request go through the handler then it is easy to solve.
However your script adding technique is then not goin to work.
An alternative that will work is if you add script like this:
```javascript
    var JS= document.createElement('script');
    //Let the handler do the request and have the result in the variable code.
    JS.text= code;
    document.body.appendChild(JS);
```

**Comment by andersevenrud** [comment]
But you did not answer my question :p 

> I saw that this particular case is a bit more difficult as it is used for the src attribute of a script tag that is added to the page.

This is what I meant by "resources" earlier. Images, scripts and stylesheets all do this.

> An alternative that will work is if you add script like this:

This is really not an option at the moment (I think). With the Node and PHP server you can pass resources through your scripts -- so this is not an issue there.

**Comment by andersevenrud** [comment]
Can't you do that in ISS ? Like proxy all requests through your server code ?

**Comment by andersevenrud** [comment]
Can't you do that in ISS ? Like proxy/redirect all requests through your server code ? (mod_rewrite)

**Comment by RickGlimmer** [comment]
```
/FS/get/?path={urlencodedpath}
```
This would be fine.

An alternative, and maybe even easier would be to allow the handler to modify the url.
The handler is the one that talks to the backend and in my opinion each request (certainly the ones that uses a users folders) should go through it.

**Comment by andersevenrud** [comment]
> An alternative, and maybe even easier would be to allow the handler to modify the url.

I will plug this in... It's an obviously better choice actually :)

**Comment by RickGlimmer** [comment]
Great!

**Comment by andersevenrud** [comment]
Allright, mr @RickGlimmer . Handler now has `::getVFSPath()` :)

https://github.com/os-js/OS.js/blob/master/src/client/javascript/handler.js#L296

**Comment by andersevenrud** [comment]
Let me know if that name sucks... it was the first that came to mind (naming is *hard*)

**Comment by andersevenrud** [comment]
Also changed `FS:xhr` to `FS:get`

**Comment by RickGlimmer** [comment]
Thanks! The name seems fine, but i reserve the right to change my mind. :)

**Comment by andersevenrud** [comment]
This all made it into the Arduino branch! Total win, because next update will have all these updates

**Comment by khoaakt** [comment]
Ahem, long time do not feedback for osjs :smile: 
I will talk about the desktop. Now, it's just support 'Shortcut' and can't copy or create file or folder on it. So, turn desktop into a folder like other operating systems!

**Comment by andersevenrud** [comment]
@khoaakt I'll look into that, but the current desktop icon view was designed to work as shortcuts.

I can maybe provide both solutions and have it in Settings

**Comment by andersevenrud** [comment]
Closing this issue. The remaining stuff will get its own issues when I get started
